// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {shared} from '../models';
import {backend} from '../models';

export function AnalyzeDashboardWithAI(arg1:shared.AnalyzeDashboardInput):Promise<shared.AIAnalysisRecord>;

export function CalculateQuote(arg1:shared.CalculateQuoteInput):Promise<shared.QuoteResult>;

export function CreateAIModel(arg1:shared.CreateAIModelInput):Promise<shared.AIModel>;

export function CreateAIProvider(arg1:shared.CreateAIProviderInput):Promise<shared.AIProvider>;

export function CreateBillingCategory(arg1:shared.CreateBillingCategoryInput):Promise<shared.BillingCategory>;

export function CreateCategory(arg1:shared.CreateCategoryInput):Promise<shared.Category>;

export function CreateTransaction(arg1:shared.CreateTransactionInput):Promise<shared.Transaction>;

export function DeleteAIAnalysis(arg1:string):Promise<void>;

export function DeleteBillingCategory(arg1:string):Promise<void>;

export function DeleteBudget(arg1:string):Promise<void>;

export function DeleteCategory(arg1:string):Promise<void>;

export function ExportTransactionsCSV(arg1:shared.TransactionFilterInput):Promise<string>;

export function ExportWeeklyCSV(arg1:number):Promise<string>;

export function ExportWeeklyLedgerXLSX(arg1:number):Promise<string>;

export function GetAIAnalyses():Promise<Array<shared.AIAnalysisRecord>>;

export function GetAIConfiguration():Promise<shared.AIConfiguration>;

export function GetAIModels(arg1:string):Promise<Array<shared.AIModel>>;

export function GetAIProviders():Promise<Array<shared.AIProvider>>;

export function GetAppSettings():Promise<shared.AppSettings>;

export function GetAppStatus():Promise<backend.AppStatus>;

export function GetBalance():Promise<shared.Balance>;

export function GetBillingCategories():Promise<Array<shared.BillingCategory>>;

export function GetBudgets():Promise<Array<shared.Budget>>;

export function GetCategories():Promise<Array<shared.Category>>;

export function GetCategoryRanking(arg1:shared.CategoryRankingInput):Promise<shared.CategoryRankingResult>;

export function GetDashboardSummary():Promise<shared.DashboardSummary>;

export function GetLegalInfo():Promise<shared.LegalInfo>;

export function GetTransactions():Promise<Array<shared.Transaction>>;

export function GetTransactionsFiltered(arg1:shared.TransactionFilterInput):Promise<Array<shared.Transaction>>;

export function GetWeeklySummary(arg1:number):Promise<shared.WeeklySummary>;

export function GetWeeklyTransactions(arg1:number):Promise<Array<shared.Transaction>>;

export function SaveAIConfiguration(arg1:shared.SaveAIConfigurationInput):Promise<shared.AIConfiguration>;

export function SaveAppSettings(arg1:shared.AppSettings):Promise<shared.AppSettings>;

export function SaveBudget(arg1:shared.SaveBudgetInput):Promise<shared.Budget>;

export function SetLegalInfo(arg1:shared.LegalInfo):Promise<void>;

export function UpdateBillingCategory(arg1:shared.UpdateBillingCategoryInput):Promise<shared.BillingCategory>;

export function UpdateCategory(arg1:shared.UpdateCategoryInput):Promise<shared.Category>;
