// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeDashboardWithAI(arg1) {
  return window['go']['backend']['App']['AnalyzeDashboardWithAI'](arg1);
}

export function CalculateQuote(arg1) {
  return window['go']['backend']['App']['CalculateQuote'](arg1);
}

export function CreateAIModel(arg1) {
  return window['go']['backend']['App']['CreateAIModel'](arg1);
}

export function CreateAIProvider(arg1) {
  return window['go']['backend']['App']['CreateAIProvider'](arg1);
}

export function CreateBillingCategory(arg1) {
  return window['go']['backend']['App']['CreateBillingCategory'](arg1);
}

export function CreateCategory(arg1) {
  return window['go']['backend']['App']['CreateCategory'](arg1);
}

export function CreateTransaction(arg1) {
  return window['go']['backend']['App']['CreateTransaction'](arg1);
}

export function DeleteAIAnalysis(arg1) {
  return window['go']['backend']['App']['DeleteAIAnalysis'](arg1);
}

export function DeleteBillingCategory(arg1) {
  return window['go']['backend']['App']['DeleteBillingCategory'](arg1);
}

export function DeleteBudget(arg1) {
  return window['go']['backend']['App']['DeleteBudget'](arg1);
}

export function DeleteCategory(arg1) {
  return window['go']['backend']['App']['DeleteCategory'](arg1);
}

export function ExportTransactionsCSV(arg1) {
  return window['go']['backend']['App']['ExportTransactionsCSV'](arg1);
}

export function ExportWeeklyCSV(arg1) {
  return window['go']['backend']['App']['ExportWeeklyCSV'](arg1);
}

export function ExportWeeklyLedgerXLSX(arg1) {
  return window['go']['backend']['App']['ExportWeeklyLedgerXLSX'](arg1);
}

export function GetAIAnalyses() {
  return window['go']['backend']['App']['GetAIAnalyses']();
}

export function GetAIConfiguration() {
  return window['go']['backend']['App']['GetAIConfiguration']();
}

export function GetAIModels(arg1) {
  return window['go']['backend']['App']['GetAIModels'](arg1);
}

export function GetAIProviders() {
  return window['go']['backend']['App']['GetAIProviders']();
}

export function GetAppSettings() {
  return window['go']['backend']['App']['GetAppSettings']();
}

export function GetAppStatus() {
  return window['go']['backend']['App']['GetAppStatus']();
}

export function GetBalance() {
  return window['go']['backend']['App']['GetBalance']();
}

export function GetBillingCategories() {
  return window['go']['backend']['App']['GetBillingCategories']();
}

export function GetBudgets() {
  return window['go']['backend']['App']['GetBudgets']();
}

export function GetCategories() {
  return window['go']['backend']['App']['GetCategories']();
}

export function GetCategoryRanking(arg1) {
  return window['go']['backend']['App']['GetCategoryRanking'](arg1);
}

export function GetDashboardSummary() {
  return window['go']['backend']['App']['GetDashboardSummary']();
}

export function GetLegalInfo() {
  return window['go']['backend']['App']['GetLegalInfo']();
}

export function GetTransactions() {
  return window['go']['backend']['App']['GetTransactions']();
}

export function GetTransactionsFiltered(arg1) {
  return window['go']['backend']['App']['GetTransactionsFiltered'](arg1);
}

export function GetWeeklySummary(arg1) {
  return window['go']['backend']['App']['GetWeeklySummary'](arg1);
}

export function GetWeeklyTransactions(arg1) {
  return window['go']['backend']['App']['GetWeeklyTransactions'](arg1);
}

export function SaveAIConfiguration(arg1) {
  return window['go']['backend']['App']['SaveAIConfiguration'](arg1);
}

export function SaveAppSettings(arg1) {
  return window['go']['backend']['App']['SaveAppSettings'](arg1);
}

export function SaveBudget(arg1) {
  return window['go']['backend']['App']['SaveBudget'](arg1);
}

export function SetLegalInfo(arg1) {
  return window['go']['backend']['App']['SetLegalInfo'](arg1);
}

export function UpdateBillingCategory(arg1) {
  return window['go']['backend']['App']['UpdateBillingCategory'](arg1);
}

export function UpdateCategory(arg1) {
  return window['go']['backend']['App']['UpdateCategory'](arg1);
}
